name: Release

on: [ workflow_dispatch ]

jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Set up JDK 11'
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: 'Build JAR'
        run: |
          ./gradlew shadowJar

      - name: 'Get Version Number'
        run: |
          echo "::set-env name=VERSION::$(./gradlew properties -q | grep "version:" | awk '{print $2}')"

      - name: 'Publish JAR'
        uses: actions/upload-artifact@v2
        with:
          name: 'paddle-${{ env.VERSION }}-all.jar'
          path: build/shadow/paddle-${{ env.VERSION }}-all.jar

      - name: 'Create Release'
        if: contains(github.ref, 'v')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{github.ref}}
          body: |
            Paddle release
          draft: false
          prerelease: true

      - name: 'Upload Release Asset'
        if: contains(github.ref, 'v')
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/shadow/paddle-${{ env.VERSION }}-all.jar
          asset_name: paddle-${{ env.VERSION }}-all.jar
          asset_content_type: application/java-archive

      - name: 'Write Upload URL To File'
        if: contains(github.ref, 'v')
        run: |
          echo "${{ steps.create_release.outputs.upload_url }}" > upload_url.txt

      - name: 'Publish Upload URL'
        if: contains(github.ref, 'v')
        uses: actions/upload-artifact@v2
        with:
          name: 'upload_url.txt'
          path: 'upload_url.txt'

  build-images:
    name: 'Build Linux & macOS Images'
    needs: [ build-jar ]
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ]
        include:
          - os: 'ubuntu-latest'
            label: 'linux'
          - os: 'macos-latest'
            label: 'mac'
    runs-on: ${{matrix.os}}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Set up JDK 11'
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: 'Setup GraalVM environment'
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: '22.2.0'
          java: 'java11'

      - name: 'Install Native Image Plugin'
        run: |
          gu install native-image

      - name: 'Get Version Number'
        run: |
          echo "::set-env name=VERSION::$(./gradlew properties -q | grep "version:" | awk '{print $2}')"

      - name: 'Get JAR Artifact'
        uses: actions/download-artifact@v2
        with:
          name: 'paddle-${{env.VERSION}}-all.jar'

      - name: 'Download Release URL'
        if: contains(github.ref, 'v')
        uses: actions/download-artifact@v2
        with:
          name: 'upload_url.txt'

      - name: 'Set Upload URL Env Var'
        if: contains(github.ref, 'v')
        run: |
          echo "::set-env name=UPLOAD_URL::$(cat upload_url.txt)"

      - name: 'Build Linux Image'
        run: |
          ./gradlew nativeCompile -Pagent

      - name: 'Publish Linux Image'
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: 'paddle-${{env.VERSION}}-${{matrix.label}}'
          path: 'paddle-${{env.VERSION}}-all'

      - name: 'Upload Linux Image Asset'
        if: success() && contains(github.ref, 'v')
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_name: 'paddle-${{env.VERSION}}-${{matrix.label}}'
          asset_path: 'paddle-${{env.VERSION}}-all'
          asset_content_type: application/octet-stream

  publich-idea-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Set up JDK 11'
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: 'Release IDEA'
        env:
          MARKETPLACE_TOKEN: ${{ secrets.MARKETPLACE_TOKEN }}
        run: ./gradlew publishPlugin
